### ISSUE TITLE
v3.8.9 tag

### ISSUE THREAD

**Issue by inikulshin** [rabbitmq/rabbitmq-ct-helpers#49]
@pjk25 , why there are no new tags in this repo since 3.7?

After breaking https://github.com/rabbitmq/rabbitmq-ct-helpers/commit/37b5167f9e99c3090cf73d7bf840d298915b13d2 it is impossible to build custom plugins with **v3.8.9**. `make deps` brings `master` instead of non-existing tag `v3.8.9`, and fails with 

ERLC   rabbit_control_helper.erl rabbit_ct_broker_helpers.erl rabbit_ct_config_schema.erl rabbit_ct_helpers.erl rabbit_ct_proper_helpers.erl rabbit_ct_vm_helpers.erl rabbit_mgmt_test_util.erl
**src/rabbit_ct_helpers.erl:12: badly formed deprecated attribute** {is_mixed_versions,1,[85,115,101,32,105,115,95,109,105,120,101,100,95,118,101,114,115,105,111,110,115,47,48,32,105,110,115,116,101,97,100]}
erlang.mk:5452: recipe for target 'ebin/rabbitmq_ct_helpers.app' failed

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
